# ===================================================================
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
eureka:
  instance:
    appname: discovery
    instanceId: discovery:${spring.application.instance-id:${random.value}}
    hostname: localhost
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}
  client:
    fetch-registry: false
    register-with-eureka: false
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://admin:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  DataCenter: Gtmo

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['refresh', 'health', 'info']
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
  application:
    name: discovery
  security:
    user:
      name: admin
      password: ${EUREKA_USER_PASSWORD:eureka}

server:
  port: ${PORT:8761}
  servlet:
    session:
      cookie:
        http-only: true

