# ===================================================================
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
eureka:
  instance:
    hostname: localhost
    metadata-map:
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:${spring.security.user.password:admin}@localhost:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ['refresh', 'health', 'info']
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
  application:
    name: discovery
  security:
    user:
      name: admin
      password: admin

server:
  port: 8761
  servlet:
    session:
      cookie:
        http-only: true

